sudo: required
services:
  - docker

  before_install:
    - docker build -t dilzoda/react-test -f ./client/Dockerfile.dev ./client

    script:
      - docker run -e CI=true USERNAME/react-test npm test -- --coverage 

      after_success:
        -docker build dilzoda/multi-client ./client
        -docker build dilzoda/multi-nginx ./nginx
        -docker build dilzoda/multi-server ./server
        -docker build dilzoda/multi-worker ./worker
